[model]
pred_len = 168
physics_embedding = 512
num_layers = 2
text_encoder_name = "distilbert-base-uncased"
text_embedding = 768
max_length = 200
trainable = true
temperature = 1.0
projection_dim = 128
continuous_loads = true
